kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: asciidoctor/docker-asciidoctor
    pull: always
    commands:
      - asciidoctor-pdf resume.adoc
  - name: github_release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_release_api_key
      files:
        - resume.pdf
      checksum:
        - sha512
    when:
      event: tag
