kind: pipeline
type: docker
name: default

steps:
  - build: stage
    image: asciidoctor/docker-asciidoctor
    pull: always
    commands:
      - asciidoctor-pdf resume.adoc
  - name: github_releasey
    image: plugins/github-release
    api_key:
      from_secret: github_release_api_key
    files:
      - resume.pdf
    checksum:
      - sha512
    when:
      event: tag
