workspace:
  base: /resume
  path: src/github.com/razem-io/resume

pipeline:
  build:
    image: asciidoctor/docker-asciidoctor
    commands:
      - asciidoctor-pdf resume_long.adoc
      - asciidoctor-pdf resume_short.adoc
  github_release:
    image: plugins/github-release
    secrets: [ github_release_api_key ]
    files:
      - resume_long.pdf
      - resume_short.pdf
    checksum:
      - sha512
    when:
      event: tag
