workspace:
  base: /resume
  path: src/github.com/razem-io/resume

pipeline:
  build:
    image: asciidoctor/docker-asciidoctor
    commands:
      - asciidoctor-pdf resume.adoc
  github_release:
    image: plugins/github-release
    secrets: [ github_release_api_key ]
    files:
      - resume.pdf
    checksum:
      - sha512
    when:
      event: tag
