:authors: Julian Pieles
:doctitle: Resume: Julian Pieles
:published_at: 2020-05-24
ifdef::backend-pdf[:notitle:]
ifdef::backend-pdf[]
[discrete]
= {doctitle}
endif::[]

:hp-tags: resume, julian pieles, computer science, bachelor, java, scala, haxe

NOTE: Last updated on *{docdate}*

== CONTACT
+49-163-7730387 +
Norfer Weg 105, 41468 Neuss +
mailto:julian@pieles.digital[] +
https://github.com/razem-io[@ *GitHub*] +
https://stackoverflow.com/users/1029251/julian-pieles?tab=profile[@ *stackoverflow*] +
https://codereview.stackexchange.com/users/90723/julian-pieles[@ *CODE REVIEW*] +
https://www.slant.co/users/GG:113026379734376225768[@ *Slant*] +
https://www.linkedin.com/in/julianpieles/[@ *LinkedIn*] +
https://www.xing.com/profile/Julian_Pieles2/cv[@ *XING*] +

== WORK EXPERIENCE

*06/2022 - today:* HeadNap GmbH - _Monheim am Rhein, Germany_

Developing workflow automation based on Scala and Scala.js for employees with the goal of facilitating tedious and error-prone tasks. 
Having fun with automated statistical analysis and fundamental analysis in a large but modern Scala stack. 
Integrating OpenAIs Whisper and Stable Diffusion stack into business applications being used in-House on a day-to-day basis.
Automate everything around DevOps and IT.

*10/2020 - 05/2022:* AYOXXA Biosystems GmbH - _Cologne, Germany_

Working on the software which enables Ayoxxa's LUNARIS™ technology. The platform can generate high-quality proteomics data using the smallest sample volumes. It allows fully scalable quantitative validation of disease-relevant biomarkers and enables translational research.
Everything from the customer-facing Desktop Software to the single board computer agent running inside the in-house designed scanner hardware is based on Scala. Optimizing high-performance image processing, controlling of robot microscopes, introducing monitoring and logging aggregation for further analytics while maintaining the self-hosted 100 TB+ server infrastructure with a team of 4 people.

*06/2018 - 09/2020:* Valtech Mobility GmbH - _Düsseldorf, Germany_

Backend development to full extend. Working for Audi, Porsche and VW. Utilizing
the power of functional programming using Scala for scalable, complex, high
throughput and stable solutions. Building monitoring stacks to keep services
running 24/7 with influxdb, elasticsearch, telegraf and prometheus by
visualizing them in grafana or kibana. Working occasionally with Java 8-11 to keep legacy services running.

*12/2016 - 05/2018:* Valtech GmbH - _Düsseldorf, Germany_

Backend development to full extend. Working for Audi, Porsche and VW. Utilizing
the power of functional programming using Scala for scalable, complex, high
throughput and stable solutions. Building monitoring stacks to keep services
running 24/7 with influxdb, elasticsearch, telegraf and prometheus by
visualizing them in grafana or kibana. Working with Java 8 to keep legacy
services running.

*09/2014 - 11/2016:* Flinsta GmbH & Co. KG - _Düsseldorf, Germany_

I got to work with many and most of the times bleeding edge tools and frameworks. Designing algorithms from scratch, optimizing code, clustering of processing power and data analytics were the challenges I had to face during this job, in order to build a blazing fast and stable backend.

*11/2012 - 08/2014:* RockAByte GmbH - _Cologne, Germany_

My prior experiences with WebOS, Haxe and Java lead to a focus on Android and native crossplatform development. During the time at RockAByte I worked on many different projects.

*08/2011 - 12/2013:* Siemens Enterprise Communications - _Witten, Germany_

My line of work covered maintaining the custom test framework, writing new test cases, developing a module for the framework to test web frontends with selenium and developing automated tests of installations on different operating systems with vSphere and a Java connector.

*08/2011 - 09/2012:* richtwert GmbH - _Düsseldorf, Germany_

I maintained a project written in Java GWT.  I had to refactor the code of the project, in order to update libraries, implement new features an resolve bugs.

*08/2011 - 09/2012:* Northlight Games - _Düsseldorf, Germany_

A small company founded by 6 students (including myself) at the md.h Düsseldorf. During our studies Northlight Games developed several functional complete Cross-Platform games.

*03/2008 - 12/2010:* LIEBL Software - _Munich, Germany_

LIEBL Software was founded by myself with a focus on WebOS App development.

*03/2008 - Present:* Open Source

Please have a look at my projects hosted at github, the projects I contributed to and the organisations where I am a member.

== AWARDS
- Honored for "Best technical bachelor thesis of the year" at the university.
- Third place at the Game Forge Newcomer Award 2011.
- Nominated for the best WebOS Health APP of 2011.
- Placed 34 at Palm Top 100 Hot Apps Contest 2009.

== EDUCATION
*09/2010 - 09/2013:* Bachelor of Science in Gamedesign +
Mediadesign Hochschule - _Düsseldorf, Germany_

My bachelor thesis focused on mobile Cross-Platform development with the topic: _The Development of a Porting-Pipeline Using the Example of ActionScript 3-Games on the Basis of Haxe-Language and OpenFL-Framework for Cross-Platform, Mobile Games_

*09/2008 - 09/2010* State certified Industrialtechnologist with emphasis on Data Technology +
Siemens Technik Akademie - _Munich, Germany_

=== CERTIFICATES
- Bullats / Business Language Testing Service CEF/ALTE Level: C1/4
- MCSA / Microsoft Certified Server Administrator (Windows Server 2003)
- MCDST / Microsoft Certified Desktop Support Technician (Windows XP)

<<<
== SKILLS AND TECHNICAL EXPERIENCE
[cols="h,n,n,n"  options="header"]
|===
|
|Best
|Good
|Medium

|Programming Languages
|Java 7 - 19, Scala 2.11 - 2.13, Haxe 2 & 3
|C#, JavaScript, CoffeeScript
|Python, C++

|Frameworks
|Play Framework, Laminar
|Akka, Guice, Scalatra, Semantic UI, Bootstrap
|Spring

|Databases
|SQL, MongoDB, Elasticsearch, MapDB, OrientDB, InfluxDB
|Redis
|Cassandra

|Message Queues
|Kafka, MQTT
|Kinesis
|RabbitMQ

|Operating Systems
|Linux (arch, alpine, debian), macOS, Windows, Android, iOS, ChromeOS
|Linux (Red Hat, CentOS), FreeBSD (TrueNAS), OpenSolaris (SmartOS) 
|

|IDEs / Editors
|IntelliJ IDEA, Visual Studio Code, Nano
|Sublime 2 & 3
|Emacs, vi(m)

|Configuration, Markup, Universal Formats
|JSON Schema, Protobuf, gRPC, Markdown, AsciiDoc, Latex, HOCON, YAML, JSON, XML
|TOML
|Protobuf

|Platforms
|Server Backend, Web/REST, Web Frontend
|Mobile (Android, Cross-Platform), Desktop
|

|Build Tools
|Gradle, SBT
|Maven
|Ant, Makefiles

|Version Control
|Git
|Mercurial, SVN
|

|Collaboration
|Confluence, JIRA, Redmine, BookStack, Slack, Teams
|Gitlab, Trac
|

|Continuous Integration
|Jenkins, Drone
|Gitlab CI
|

|DevOps
|Docker, docker-compose, Prometheus, ELK-Stack, Telegraf
|Kubernetes, Helm
|Terraform

|Selfhosting
|Docker, docker-compose, Traefik, Nextcloud, Bitwarden/Vaultwarden, Elasticsearch, InfluxDB, Telegraf, Grafana, Kibana, Jitsi, BigBlueButton, mailcow, Mail-in-a-Box, Kanboard, Wordpress, Gitea, BookStack, Monica, PiVPN, blocky
|Drone, OpenLDAP, Portainer, Seafile, huginn
|FileCloud

|Home Automation
|Home Assistant, RaspberryMatic (Homematic), Raspbee (Deconz), MQTT
|OpenHAB, KNX
|

|Languages
|German, English
|
|French

|===

== SOCIAL
- Student council / _Class 10 - 13_
- Class representative / _Class 11 - 13_
- Head boy / _Class 12 - 13_
- Member of the student government in Düsseldorf / _2005 - 2007_
- Term speaker (Gamedesign)  MD.H Düsseldorf / _2010 - 2011_
- Member of a multigeneration homes project / _2016 - 2018_
